# Generated by Django 3.0.7 on 2021-04-11 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('raw_material', models.ManyToManyField(to='home.RawMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distace', models.IntegerField()),
                ('from_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From', to='home.Spot')),
                ('to_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To', to='home.Spot')),
            ],
        ),
        migrations.AddField(
            model_name='industry',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Spot'),
        ),
    ]
