# Generated by Django 3.0.7 on 2021-04-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210412_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
