# Generated by Django 3.0.7 on 2021-04-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210412_0606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resources_on_spot',
            new_name='RawMaterialOnSpot',
        ),
    ]
