# Generated by Django 3.0.7 on 2021-04-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210412_0608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawMaterialOnSpot',
            new_name='SpotRawMaterial',
        ),
    ]
