# Generated by Django 3.0.7 on 2021-04-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_team_ecoins'),
        ('home', '0010_auto_20210412_0609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawMaterial',
            new_name='Item',
        ),
    ]
