# Generated by Django 3.0.7 on 2021-04-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_manufacture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manufacture',
        ),
    ]
