# Generated by Django 3.0.7 on 2021-04-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210414_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='raw_material',
            field=models.ForeignKey(blank=True, limit_choices_to={'raw_material': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RawMaterial', to='home.Item'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='product',
            field=models.ForeignKey(blank=True, limit_choices_to={'product': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product', to='home.Item'),
        ),
    ]
