# Generated by Django 3.0.7 on 2021-04-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210414_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotrawmaterial',
            name='raw_material',
            field=models.ForeignKey(blank=True, limit_choices_to={'raw_material': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Item'),
        ),
    ]
