# Generated by Django 3.0.7 on 2021-04-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_item_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='category_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='category_3',
            field=models.BooleanField(default=False),
        ),
    ]
