# Generated by Django 3.0.7 on 2021-04-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
