# Generated by Django 3.0.7 on 2021-04-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_spot_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_1', models.BooleanField(default=False)),
                ('season_2', models.BooleanField(default=False)),
                ('season_3', models.BooleanField(default=False)),
                ('season_4', models.BooleanField(default=False)),
            ],
        ),
    ]
