# Generated by Django 3.0.7 on 2021-04-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='raw_material_cost',
            field=models.IntegerField(default=0),
        ),
    ]
