# Generated by Django 3.2 on 2021-04-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_item_raw_material_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotrawmaterial',
            name='lat',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='spotrawmaterial',
            name='lng',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
