# Generated by Django 3.2 on 2021-04-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210422_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotrawmaterial',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='spotrawmaterial',
            name='lng',
        ),
        migrations.AddField(
            model_name='spot',
            name='lat',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='spot',
            name='lng',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
