# Generated by Django 3.0.7 on 2021-04-10 20:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(max_length=50)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(help_text='Add country code before the contact no.', max_length=128, region=None)),
                ('roll_no', models.CharField(default=' ', help_text='Enter your Roll No. if you are studying in TIET otherwise enter your college name', max_length=100, verbose_name='Roll no/ College Name')),
                ('are_you_a_thapar_student', models.BooleanField(default=True, verbose_name='Are you a thapar student?')),
                ('year_of_study', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('position', models.CharField(blank=True, choices=[('CEO', 'CEO'), ('CTO', 'CTO'), ('CFO', 'CFO'), ('CMO', 'CMO'), ('HR', 'HR')], default=None, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
