# Generated by Django 3.0.7 on 2021-04-10 23:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210411_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='contact_no3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Add country code before the contact no.', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact_no4',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Add country code before the contact no.', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='team',
            name='email3',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='team',
            name='email4',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
