# Generated by Django 3.0.7 on 2021-04-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('user', '0003_auto_20210411_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Industry'),
        ),
    ]
