# Generated by Django 3.0.7 on 2021-04-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ecoins',
            field=models.IntegerField(default=0),
        ),
    ]
