# Generated by Django 3.0.7 on 2021-04-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210414_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ecoins',
            field=models.IntegerField(default=1000),
        ),
    ]
