# Generated by Django 3.0.7 on 2021-04-14 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210414_1956'),
        ('user', '0009_auto_20210414_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(limit_choices_to={'product': True}, on_delete=django.db.models.deletion.CASCADE, to='home.Item')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('raw_material', models.ForeignKey(limit_choices_to={'raw_material': True}, on_delete=django.db.models.deletion.CASCADE, to='home.Item')),
                ('spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Spot')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='manufacture',
            name='product',
        ),
        migrations.RemoveField(
            model_name='manufacture',
            name='team_name',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Manufacture',
        ),
    ]
