# Generated by Django 3.0.7 on 2021-04-14 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210414_2029'),
        ('user', '0010_auto_20210414_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromTeam', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Item')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToTeam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
