# Generated by Django 3.0.7 on 2021-04-19 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210418_0402'),
        ('user', '0015_alter_team_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='RawMaterialBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_1', models.IntegerField(default=0)),
                ('quantity_2', models.IntegerField(default=0)),
                ('raw_material_1', models.ForeignKey(limit_choices_to={'raw_material': True}, on_delete=django.db.models.deletion.CASCADE, related_name='RawMaterial1', to='home.Item')),
                ('raw_material_2', models.ForeignKey(limit_choices_to={'raw_material': True}, on_delete=django.db.models.deletion.CASCADE, related_name='RawMaterial2', to='home.Item')),
                ('spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Spot')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
