# Generated by Django 3.0.7 on 2021-04-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_team_first_name'),
        ('user', '0019_sendrequest_is_visible'),
    ]

    operations = [
    ]
