# Generated by Django 3.0.7 on 2021-04-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210422_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrequest',
            name='cost',
            field=models.IntegerField(verbose_name='Cost Per Unit'),
        ),
    ]
