# Generated by Django 3.0.7 on 2021-04-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210422_2328'),
        ('user', '0023_alter_team_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialcart',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.Spot', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
