# Generated by Django 3.0.7 on 2021-04-23 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210422_2329'),
        ('user', '0024_auto_20210423_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellus',
            name='product',
        ),
        migrations.AddField(
            model_name='sellus',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Item'),
        ),
    ]
