# Generated by Django 3.0.7 on 2021-04-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20210423_2306'),
        ('user', '0026_alter_team_first_name'),
    ]

    operations = [
    ]
